-- MySQL Script generated by MySQL Workbench
-- Sun Jul 16 19:31:57 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CP4
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CP4
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CP4` DEFAULT CHARACTER SET utf8 ;
USE `CP4` ;

-- -----------------------------------------------------
-- Table `CP4`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CP4`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pseudo` VARCHAR(45) NOT NULL,
  `hashed_password` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

INSERT into user (pseudo, hashed_password) VALUES ('Yuki', '$argon2id$v=19$m=65536,t=5,p=1$JghS5crVWZwjDe2GBG2BYA$S/f+cMapdWccEWwCLm+IX8YveQxmJ+PKMVgkAxmlGF4');

-- -----------------------------------------------------
-- Table `CP4`.`movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CP4`.`movie` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(80) NOT NULL,
  `director` VARCHAR(80) NULL,
  `seen` DATE NULL,
  `is_seen` TINYINT NULL,
  `rating` INT NULL,
  `owned` TINYINT NULL,
  `is_lent` TINYINT NULL,
  `lent_to` VARCHAR(80) NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_movie_user0`
    FOREIGN KEY (`user_id`)
    REFERENCES `CP4`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CP4`.`book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CP4`.`book` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(80) NOT NULL,
  `author` VARCHAR(80) NULL,
  `read` DATE NULL,
  `is_read` TINYINT NULL,
  `rating` INT NULL,
  `owned` TINYINT NULL,
  `is_lent` TINYINT NULL,
  `lent_to` VARCHAR(80) NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_movie_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `CP4`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CP4`.`album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CP4`.`album` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(80) NOT NULL,
  `artist` VARCHAR(80) NULL,
  `listened` DATE NULL,
  `is_listened` TINYINT NULL,
  `rating` INT NULL,
  `owned` TINYINT NULL,
  `is_lent` TINYINT NULL,
  `lent_to` VARCHAR(80) NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_movie_user2`
    FOREIGN KEY (`user_id`)
    REFERENCES `CP4`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CP4`.`comic_book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CP4`.`comic_book` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(80) NOT NULL,
  `artist` VARCHAR(80) NULL,
  `scenarist` VARCHAR(80) NULL,
  `read` DATE NULL,
  `is_read` TINYINT NULL,
  `rating` INT NULL,
  `owned` TINYINT NULL,
  `is_lent` TINYINT NULL,
  `lent_to` VARCHAR(80) NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_movie_user3`
    FOREIGN KEY (`user_id`)
    REFERENCES `CP4`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
